export const flashcards = [
    { ideograma: "你好！", pinyin: "Nǐ hǎo!", traducao: "Olá!" },
    { ideograma: "谢谢你。", pinyin: "Xièxiè nǐ.", traducao: "Obrigado(a)." },
    { ideograma: "再见！", pinyin: "Zàijiàn!", traducao: "Adeus!" },
    { ideograma: "我叫李明。", pinyin: "Wǒ jiào Lǐ Míng.", traducao: "Eu me chamo Li Ming." },
    { ideograma: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", traducao: "Qual é o seu nome?" },
    { ideograma: "我是学生。", pinyin: "Wǒ shì xuéshēng.", traducao: "Eu sou estudante." },
    { ideograma: "他是老师。", pinyin: "Tā shì lǎoshī.", traducao: "Ele é professor." },
    { ideograma: "你好吗？", pinyin: "Nǐ hǎo ma?", traducao: "Como você está?" },
    { ideograma: "我很好。", pinyin: "Wǒ hěn hǎo.", traducao: "Estou bem." },
    { ideograma: "你呢？", pinyin: "Nǐ ne?", traducao: "E você?" },
    { ideograma: "我也很好。", pinyin: "Wǒ yě hěn hǎo.", traducao: "Eu também estou bem." },
    { ideograma: "这是什么？", pinyin: "Zhè shì shénme?", traducao: "O que é isso?" },
    { ideograma: "那是一本书。", pinyin: "Nà shì yì běn shū.", traducao: "Aquilo é um livro." },
    { ideograma: "请问，厕所在哪里？", pinyin: "Qǐngwèn, cèsuǒ zài nǎlǐ?", traducao: "Com licença, onde fica o banheiro?" },
    { ideograma: "对不起。", pinyin: "Duìbuqǐ.", traducao: "Desculpe." },
    { ideograma: "没关系。", pinyin: "Méi guānxi.", traducao: "Não tem problema." },
    { ideograma: "请坐。", pinyin: "Qǐng zuò.", traducao: "Por favor, sente-se." },
    { ideograma: "你会说中文吗？", pinyin: "Nǐ huì shuō Zhōngwén ma?", traducao: "Você sabe falar chinês?" },
    { ideograma: "我会说一点儿。", pinyin: "Wǒ huì shuō yìdiǎnr.", traducao: "Eu sei falar um pouco." },
    { ideograma: "你家在哪儿？", pinyin: "Nǐ jiā zài nǎr?", traducao: "Onde fica sua casa?" },
    { ideograma: "我家在北京。", pinyin: "Wǒ jiā zài Běijīng.", traducao: "Minha casa fica em Pequim." },
    { ideograma: "今天天气很好。", pinyin: "Jīntiān tiānqì hěn hǎo.", traducao: "O tempo está muito bom hoje." },
    { ideograma: "你喜欢吃什么？", pinyin: "Nǐ xǐhuan chī shénme?", traducao: "O que você gosta de comer?" },
    { ideograma: "我喜欢吃苹果。", pinyin: "Wǒ xǐhuan chī píngguǒ.", traducao: "Eu gosto de comer maçã." },
    { ideograma: "这是谁的书？", pinyin: "Zhè shì shéi de shū?", traducao: "De quem é este livro?" },
    { ideograma: "那是我的书。", pinyin: "Nà shì wǒ de shū.", traducao: "Aquele é meu livro." },
    { ideograma: "现在几点？", pinyin: "Xiànzài jǐ diǎn?", traducao: "Que horas são agora?" },
    { ideograma: "现在三点半。", pinyin: "Xiànzài sān diǎn bàn.", traducao: "Agora são três e meia." },
    { ideograma: "你喜欢看电影吗？", pinyin: "Nǐ xǐhuan kàn diànyǐng ma?", traducao: "Você gosta de assistir filmes?" },
    { ideograma: "我很喜欢。", pinyin: "Wǒ hěn xǐhuan.", traducao: "Eu gosto muito." },
    { ideograma: "你有兄弟姐妹吗？", pinyin: "Nǐ yǒu xiōngdì jiěmèi ma?", traducao: "Você tem irmãos?" },
    { ideograma: "我有一个姐姐。", pinyin: "Wǒ yǒu yí gè jiějie.", traducao: "Eu tenho uma irmã mais velha." },
    { ideograma: "你会开车吗？", pinyin: "Nǐ huì kāichē ma?", traducao: "Você sabe dirigir?" },
    { ideograma: "我不会开车。", pinyin: "Wǒ bú huì kāichē.", traducao: "Eu não sei dirigir." },
    { ideograma: "这件衣服多少钱？", pinyin: "Zhè jiàn yīfu duōshǎo qián?", traducao: "Quanto custa esta roupa?" },
    { ideograma: "五十块钱。", pinyin: "Wǔshí kuài qián.", traducao: "Cinquenta yuans." },
    { ideograma: "你每天几点起床？", pinyin: "Nǐ měitiān jǐ diǎn qǐchuáng?", traducao: "Que horas você acorda todo dia?" },
    { ideograma: "我每天七点起床。", pinyin: "Wǒ měitiān qī diǎn qǐchuáng.", traducao: "Eu acordo às sete todos os dias." },
    { ideograma: "你周末做什么？", pinyin: "Nǐ zhōumò zuò shénme?", traducao: "O que você faz no fim de semana?" },
    { ideograma: "我喜欢去公园。", pinyin: "Wǒ xǐhuan qù gōngyuán.", traducao: "Eu gosto de ir ao parque." },
    { ideograma: "你想去哪里旅行？", pinyin: "Nǐ xiǎng qù nǎlǐ lǚxíng?", traducao: "Para onde você quer viajar?" },
    { ideograma: "我想去日本。", pinyin: "Wǒ xiǎng qù Rìběn.", traducao: "Eu quero ir para o Japão." },
    { ideograma: "你会用筷子吗？", pinyin: "Nǐ huì yòng kuàizi ma?", traducao: "Você sabe usar hashis?" },
    { ideograma: "我会一点儿。", pinyin: "Wǒ huì yìdiǎnr.", traducao: "Eu sei um pouco." },
    { ideograma: "你住在哪个城市？", pinyin: "Nǐ zhù zài nǎge chéngshì?", traducao: "Em que cidade você mora?" },
    { ideograma: "我住在上海。", pinyin: "Wǒ zhù zài Shànghǎi.", traducao: "Eu moro em Xangai." },
    { ideograma: "你最喜欢的颜色是什么？", pinyin: "Nǐ zuì xǐhuan de yánsè shì shénme?", traducao: "Qual é a sua cor favorita?" },
    { ideograma: "我最喜欢蓝色。", pinyin: "Wǒ zuì xǐhuan lánsè.", traducao: "Minha cor favorita é azul." },
    { ideograma: "你有宠物吗？", pinyin: "Nǐ yǒu chǒngwù ma?", traducao: "Você tem animais de estimação?" },
    { ideograma: "我有一只狗。", pinyin: "Wǒ yǒu yì zhī gǒu.", traducao: "Eu tenho um cachorro." },
    { ideograma: "今天是星期几？", pinyin: "Jīntiān shì xīngqī jǐ?", traducao: "Que dia da semana é hoje?" },
    { ideograma: "今天是星期三。", pinyin: "Jīntiān shì xīngqī sān.", traducao: "Hoje é quarta-feira." },
    { ideograma: "你明天有空吗？", pinyin: "Nǐ míngtiān yǒu kòng ma?", traducao: "Você está livre amanhã?" },
    { ideograma: "对不起，我没有时间。", pinyin: "Duìbuqǐ, wǒ méiyǒu shíjiān.", traducao: "Desculpe, eu não tenho tempo." },
    { ideograma: "你会做饭吗？", pinyin: "Nǐ huì zuòfàn ma?", traducao: "Você sabe cozinhar?" },
    { ideograma: "我会做一点儿。", pinyin: "Wǒ huì zuò yìdiǎnr.", traducao: "Eu sei cozinhar um pouco." },
    { ideograma: "你喜欢吃辣的吗？", pinyin: "Nǐ xǐhuan chī là de ma?", traducao: "Você gosta de comida apimentada?" },
    { ideograma: "我不太喜欢吃辣。", pinyin: "Wǒ bú tài xǐhuan chī là.", traducao: "Eu não gosto muito de comida apimentada." },
    { ideograma: "你喜欢喝咖啡还是茶？", pinyin: "Nǐ xǐhuan hē kāfēi háishì chá?", traducao: "Você prefere café ou chá?" },
    { ideograma: "我更喜欢喝咖啡。", pinyin: "Wǒ gèng xǐhuan hē kāfēi.", traducao: "Eu prefiro café." },
    { ideograma: "这道菜怎么样？", pinyin: "Zhè dào cài zěnmeyàng?", traducao: "Como está este prato?" },
    { ideograma: "很好吃！", pinyin: "Hěn hǎochī!", traducao: "Está delicioso!" },
    { ideograma: "你喜欢运动吗？", pinyin: "Nǐ xǐhuan yùndòng ma?", traducao: "Você gosta de esportes?" },
    { ideograma: "我喜欢跑步。", pinyin: "Wǒ xǐhuan pǎobù.", traducao: "Eu gosto de correr." },
    { ideograma: "你周末常常做什么？", pinyin: "Nǐ zhōumò chángcháng zuò shénme?", traducao: "O que você costuma fazer nos fins de semana?" },
    { ideograma: "我常常看书。", pinyin: "Wǒ chángcháng kàn shū.", traducao: "Eu costumo ler livros." },
    { ideograma: "你什么时候去上班？", pinyin: "Nǐ shénme shíhòu qù shàngbān?", traducao: "Quando você vai para o trabalho?" },
    { ideograma: "我早上八点去上班。", pinyin: "Wǒ zǎoshang bā diǎn qù shàngbān.", traducao: "Eu vou trabalhar às oito da manhã." },
    { ideograma: "你喜欢中国文化吗？", pinyin: "Nǐ xǐhuan Zhōngguó wénhuà ma?", traducao: "Você gosta da cultura chinesa?" },
    { ideograma: "我很喜欢中国文化。", pinyin: "Wǒ hěn xǐhuan Zhōngguó wénhuà.", traducao: "Eu gosto muito da cultura chinesa." },
    { ideograma: "你去过中国吗？", pinyin: "Nǐ qù guò Zhōngguó ma?", traducao: "Você já foi para a China?" },
    { ideograma: "我还没有去过。", pinyin: "Wǒ hái méiyǒu qù guò.", traducao: "Ainda não fui." },
    { ideograma: "你最近忙吗？", pinyin: "Nǐ zuìjìn máng ma?", traducao: "Você tem estado ocupado ultimamente?" },
    { ideograma: "我最近很忙。", pinyin: "Wǒ zuìjìn hěn máng.", traducao: "Tenho estado muito ocupado." },
    { ideograma: "你喜欢读书吗？", pinyin: "Nǐ xǐhuan dúshū ma?", traducao: "Você gosta de ler?" },
    { ideograma: "我每天都读书。", pinyin: "Wǒ měitiān dōu dúshū.", traducao: "Eu leio todos os dias." },
    { ideograma: "你累了吗？", pinyin: "Nǐ lèi le ma?", traducao: "Você está cansado?" },
    { ideograma: "我有点儿累了。", pinyin: "Wǒ yǒudiǎnr lèi le.", traducao: "Estou um pouco cansado." },
    { ideograma: "你觉得这个电影怎么样？", pinyin: "Nǐ juéde zhège diànyǐng zěnmeyàng?", traducao: "O que você achou deste filme?" },
    { ideograma: "我觉得很有意思。", pinyin: "Wǒ juéde hěn yǒu yìsi.", traducao: "Achei muito interessante." },
    { ideograma: "你今天忙不忙？", pinyin: "Nǐ jīntiān máng bù máng?", traducao: "Você está ocupado hoje?" },
    { ideograma: "我今天不太忙。", pinyin: "Wǒ jīntiān bú tài máng.", traducao: "Hoje não estou muito ocupado." },
    { ideograma: "你会游泳吗？", pinyin: "Nǐ huì yóuyǒng ma?", traducao: "Você sabe nadar?" },
    { ideograma: "我不会游泳。", pinyin: "Wǒ bú huì yóuyǒng.", traducao: "Eu não sei nadar." },
    { ideograma: "这是什么地方？", pinyin: "Zhè shì shénme dìfang?", traducao: "Que lugar é este?" },
    { ideograma: "这是一个公园。", pinyin: "Zhè shì yí gè gōngyuán.", traducao: "Este é um parque." },
    { ideograma: "你的爱好是什么？", pinyin: "Nǐ de àihào shì shénme?", traducao: "Qual é o seu hobby?" },
    { ideograma: "我喜欢听音乐和看书。", pinyin: "Wǒ xǐhuan tīng yīnyuè hé kàn shū.", traducao: "Eu gosto de ouvir música e ler livros." },
    { ideograma: "你每天怎么去学校？", pinyin: "Nǐ měitiān zěnme qù xuéxiào?", traducao: "Como você vai para a escola todos os dias?" },
    { ideograma: "我坐公交车去学校。", pinyin: "Wǒ zuò gōngjiāochē qù xuéxiào.", traducao: "Eu pego o ônibus para a escola." },
    { ideograma: "你认识这个人吗？", pinyin: "Nǐ rènshi zhège rén ma?", traducao: "Você conhece essa pessoa?" },
    { ideograma: "我不认识他。", pinyin: "Wǒ bú rènshi tā.", traducao: "Eu não o conheço." },
    { ideograma: "这个东西贵不贵？", pinyin: "Zhège dōngxi guì bú guì?", traducao: "Esta coisa é cara?" },
    { ideograma: "不太贵，很便宜。", pinyin: "Bú tài guì, hěn piányi.", traducao: "Não é muito caro, é barato." },
    { ideograma: "你喜欢吃什么水果？", pinyin: "Nǐ xǐhuan chī shénme shuǐguǒ?", traducao: "Que frutas você gosta de comer?" },
    { ideograma: "我喜欢吃西瓜和苹果。", pinyin: "Wǒ xǐhuan chī xīguā hé píngguǒ.", traducao: "Eu gosto de melancia e maçã." },
    { ideograma: "你去哪儿？", pinyin: "Nǐ qù nǎr?", traducao: "Para onde você está indo?" },
    { ideograma: "我去超市买东西。", pinyin: "Wǒ qù chāoshì mǎi dōngxi.", traducao: "Estou indo ao mercado comprar coisas." },
    { ideograma: "天气怎么样？", pinyin: "Tiānqì zěnmeyàng?", traducao: "Como está o tempo?" },
    { ideograma: "你好！", pinyin: "Nǐ hǎo!", traducao: "Olá!" },
    { ideograma: "谢谢你。", pinyin: "Xièxiè nǐ.", traducao: "Obrigado(a)." },
    { ideograma: "再见！", pinyin: "Zàijiàn!", traducao: "Adeus!" },
    { ideograma: "我叫李明。", pinyin: "Wǒ jiào Lǐ Míng.", traducao: "Eu me chamo Li Ming." },
    { ideograma: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", traducao: "Qual é o seu nome?" },
    { ideograma: "我是学生。", pinyin: "Wǒ shì xuéshēng.", traducao: "Eu sou estudante." },
    { ideograma: "他是老师。", pinyin: "Tā shì lǎoshī.", traducao: "Ele é professor." },
    { ideograma: "你好吗？", pinyin: "Nǐ hǎo ma?", traducao: "Como você está?" },
    { ideograma: "我很好。", pinyin: "Wǒ hěn hǎo.", traducao: "Estou bem." },
    { ideograma: "你呢？", pinyin: "Nǐ ne?", traducao: "E você?" },
    { ideograma: "我也很好。", pinyin: "Wǒ yě hěn hǎo.", traducao: "Eu também estou bem." },
    { ideograma: "这是什么？", pinyin: "Zhè shì shénme?", traducao: "O que é isso?" },
    { ideograma: "那是一本书。", pinyin: "Nà shì yì běn shū.", traducao: "Aquilo é um livro." },
    { ideograma: "请问，厕所在哪里？", pinyin: "Qǐngwèn, cèsuǒ zài nǎlǐ?", traducao: "Com licença, onde fica o banheiro?" },
    { ideograma: "对不起。", pinyin: "Duìbuqǐ.", traducao: "Desculpe." },
    { ideograma: "没关系。", pinyin: "Méi guānxi.", traducao: "Não tem problema." },
    { ideograma: "请坐。", pinyin: "Qǐng zuò.", traducao: "Por favor, sente-se." },
    { ideograma: "你会说中文吗？", pinyin: "Nǐ huì shuō Zhōngwén ma?", traducao: "Você sabe falar chinês?" },
    { ideograma: "我会说一点儿。", pinyin: "Wǒ huì shuō yìdiǎnr.", traducao: "Eu sei falar um pouco." },
    { ideograma: "你家在哪儿？", pinyin: "Nǐ jiā zài nǎr?", traducao: "Onde fica sua casa?" },
    { ideograma: "我家在北京。", pinyin: "Wǒ jiā zài Běijīng.", traducao: "Minha casa fica em Pequim." },
    { ideograma: "今天天气很好。", pinyin: "Jīntiān tiānqì hěn hǎo.", traducao: "O tempo está muito bom hoje." },
    { ideograma: "你喜欢吃什么？", pinyin: "Nǐ xǐhuan chī shénme?", traducao: "O que você gosta de comer?" },
    { ideograma: "我喜欢吃苹果。", pinyin: "Wǒ xǐhuan chī píngguǒ.", traducao: "Eu gosto de comer maçã." },
    { ideograma: "这是谁的书？", pinyin: "Zhè shì shéi de shū?", traducao: "De quem é este livro?" },
    { ideograma: "那是我的书。", pinyin: "Nà shì wǒ de shū.", traducao: "Aquele é meu livro." },
    { ideograma: "现在几点？", pinyin: "Xiànzài jǐ diǎn?", traducao: "Que horas são agora?" },
    { ideograma: "现在三点半。", pinyin: "Xiànzài sān diǎn bàn.", traducao: "Agora são três e meia." },
    { ideograma: "你喜欢看电影吗？", pinyin: "Nǐ xǐhuan kàn diànyǐng ma?", traducao: "Você gosta de assistir filmes?" },
    { ideograma: "我很喜欢。", pinyin: "Wǒ hěn xǐhuan.", traducao: "Eu gosto muito." },
    { ideograma: "你有兄弟姐妹吗？", pinyin: "Nǐ yǒu xiōngdì jiěmèi ma?", traducao: "Você tem irmãos?" },
    { ideograma: "我有一个姐姐。", pinyin: "Wǒ yǒu yí gè jiějie.", traducao: "Eu tenho uma irmã mais velha." },
    { ideograma: "你会开车吗？", pinyin: "Nǐ huì kāichē ma?", traducao: "Você sabe dirigir?" },
    { ideograma: "我不会开车。", pinyin: "Wǒ bú huì kāichē.", traducao: "Eu não sei dirigir." },
    { ideograma: "这件衣服多少钱？", pinyin: "Zhè jiàn yīfu duōshǎo qián?", traducao: "Quanto custa esta roupa?" },
    { ideograma: "五十块钱。", pinyin: "Wǔshí kuài qián.", traducao: "Cinquenta yuans." },
    { ideograma: "你每天几点起床？", pinyin: "Nǐ měitiān jǐ diǎn qǐchuáng?", traducao: "Que horas você acorda todo dia?" },
    { ideograma: "我每天七点起床。", pinyin: "Wǒ měitiān qī diǎn qǐchuáng.", traducao: "Eu acordo às sete todos os dias." },
    { ideograma: "你周末做什么？", pinyin: "Nǐ zhōumò zuò shénme?", traducao: "O que você faz no fim de semana?" },
    { ideograma: "我喜欢去公园。", pinyin: "Wǒ xǐhuan qù gōngyuán.", traducao: "Eu gosto de ir ao parque." },
    { ideograma: "你想去哪里旅行？", pinyin: "Nǐ xiǎng qù nǎlǐ lǚxíng?", traducao: "Para onde você quer viajar?" },
    { ideograma: "我想去日本。", pinyin: "Wǒ xiǎng qù Rìběn.", traducao: "Eu quero ir para o Japão." },
    { ideograma: "你会用筷子吗？", pinyin: "Nǐ huì yòng kuàizi ma?", traducao: "Você sabe usar hashis?" },
    { ideograma: "我会一点儿。", pinyin: "Wǒ huì yìdiǎnr.", traducao: "Eu sei um pouco." },
    { ideograma: "你住在哪个城市？", pinyin: "Nǐ zhù zài nǎge chéngshì?", traducao: "Em que cidade você mora?" },
    { ideograma: "我住在上海。", pinyin: "Wǒ zhù zài Shànghǎi.", traducao: "Eu moro em Xangai." },
    { ideograma: "你最喜欢的颜色是什么？", pinyin: "Nǐ zuì xǐhuan de yánsè shì shénme?", traducao: "Qual é a sua cor favorita?" },
    { ideograma: "我最喜欢蓝色。", pinyin: "Wǒ zuì xǐhuan lánsè.", traducao: "Minha cor favorita é azul." },
    { ideograma: "你有宠物吗？", pinyin: "Nǐ yǒu chǒngwù ma?", traducao: "Você tem animais de estimação?" },
    { ideograma: "我有一只狗。", pinyin: "Wǒ yǒu yì zhī gǒu.", traducao: "Eu tenho um cachorro." },
    { ideograma: "今天是星期几？", pinyin: "Jīntiān shì xīngqī jǐ?", traducao: "Que dia da semana é hoje?" },
    { ideograma: "今天是星期三。", pinyin: "Jīntiān shì xīngqī sān.", traducao: "Hoje é quarta-feira." },
    { ideograma: "你明天有空吗？", pinyin: "Nǐ míngtiān yǒu kòng ma?", traducao: "Você está livre amanhã?" },
    { ideograma: "对不起，我没有时间。", pinyin: "Duìbuqǐ, wǒ méiyǒu shíjiān.", traducao: "Desculpe, eu não tenho tempo." },
    { ideograma: "你会做饭吗？", pinyin: "Nǐ huì zuòfàn ma?", traducao: "Você sabe cozinhar?" },
    { ideograma: "我会做一点儿。", pinyin: "Wǒ huì zuò yìdiǎnr.", traducao: "Eu sei cozinhar um pouco." },
    { ideograma: "你喜欢吃辣的吗？", pinyin: "Nǐ xǐhuan chī là de ma?", traducao: "Você gosta de comida apimentada?" },
    { ideograma: "我不太喜欢吃辣。", pinyin: "Wǒ bú tài xǐhuan chī là.", traducao: "Eu não gosto muito de comida apimentada." },
    { ideograma: "你喜欢喝咖啡还是茶？", pinyin: "Nǐ xǐhuan hē kāfēi háishì chá?", traducao: "Você prefere café ou chá?" },
    { ideograma: "我更喜欢喝咖啡。", pinyin: "Wǒ gèng xǐhuan hē kāfēi.", traducao: "Eu prefiro café." },
    { ideograma: "这道菜怎么样？", pinyin: "Zhè dào cài zěnmeyàng?", traducao: "Como está este prato?" },
    { ideograma: "很好吃！", pinyin: "Hěn hǎochī!", traducao: "Está delicioso!" },
    { ideograma: "你喜欢运动吗？", pinyin: "Nǐ xǐhuan yùndòng ma?", traducao: "Você gosta de esportes?" },
    { ideograma: "我喜欢跑步。", pinyin: "Wǒ xǐhuan pǎobù.", traducao: "Eu gosto de correr." },
    { ideograma: "你周末常常做什么？", pinyin: "Nǐ zhōumò chángcháng zuò shénme?", traducao: "O que você costuma fazer nos fins de semana?" },
    { ideograma: "我常常看书。", pinyin: "Wǒ chángcháng kàn shū.", traducao: "Eu costumo ler livros." },
    { ideograma: "你什么时候去上班？", pinyin: "Nǐ shénme shíhòu qù shàngbān?", traducao: "Quando você vai para o trabalho?" },
    { ideograma: "我早上八点去上班。", pinyin: "Wǒ zǎoshang bā diǎn qù shàngbān.", traducao: "Eu vou trabalhar às oito da manhã." },
    { ideograma: "你喜欢中国文化吗？", pinyin: "Nǐ xǐhuan Zhōngguó wénhuà ma?", traducao: "Você gosta da cultura chinesa?" },
    { ideograma: "我很喜欢中国文化。", pinyin: "Wǒ hěn xǐhuan Zhōngguó wénhuà.", traducao: "Eu gosto muito da cultura chinesa." },
    { ideograma: "你去过中国吗？", pinyin: "Nǐ qù guò Zhōngguó ma?", traducao: "Você já foi para a China?" },
    { ideograma: "我还没有去过。", pinyin: "Wǒ hái méiyǒu qù guò.", traducao: "Ainda não fui." },
    { ideograma: "你最近忙吗？", pinyin: "Nǐ zuìjìn máng ma?", traducao: "Você tem estado ocupado ultimamente?" },
    { ideograma: "我最近很忙。", pinyin: "Wǒ zuìjìn hěn máng.", traducao: "Tenho estado muito ocupado." },
    { ideograma: "你喜欢读书吗？", pinyin: "Nǐ xǐhuan dúshū ma?", traducao: "Você gosta de ler?" },
    { ideograma: "我每天都读书。", pinyin: "Wǒ měitiān dōu dúshū.", traducao: "Eu leio todos os dias." },
    { ideograma: "你累了吗？", pinyin: "Nǐ lèi le ma?", traducao: "Você está cansado?" },
    { ideograma: "我有点儿累了。", pinyin: "Wǒ yǒudiǎnr lèi le.", traducao: "Estou um pouco cansado." },
    { ideograma: "你觉得这个电影怎么样？", pinyin: "Nǐ juéde zhège diànyǐng zěnmeyàng?", traducao: "O que você achou deste filme?" },
    { ideograma: "我觉得很有意思。", pinyin: "Wǒ juéde hěn yǒu yìsi.", traducao: "Achei muito interessante." },
    { ideograma: "你今天忙不忙？", pinyin: "Nǐ jīntiān máng bù máng?", traducao: "Você está ocupado hoje?" },
    { ideograma: "我今天不太忙。", pinyin: "Wǒ jīntiān bú tài máng.", traducao: "Hoje não estou muito ocupado." },
    { ideograma: "你会游泳吗？", pinyin: "Nǐ huì yóuyǒng ma?", traducao: "Você sabe nadar?" },
    { ideograma: "我不会游泳。", pinyin: "Wǒ bú huì yóuyǒng.", traducao: "Eu não sei nadar." },
    { ideograma: "这是什么地方？", pinyin: "Zhè shì shénme dìfang?", traducao: "Que lugar é este?" },
    { ideograma: "这是一个公园。", pinyin: "Zhè shì yí gè gōngyuán.", traducao: "Este é um parque." },
    { ideograma: "你的爱好是什么？", pinyin: "Nǐ de àihào shì shénme?", traducao: "Qual é o seu hobby?" },
    { ideograma: "我喜欢听音乐和看书。", pinyin: "Wǒ xǐhuan tīng yīnyuè hé kàn shū.", traducao: "Eu gosto de ouvir música e ler livros." },
    { ideograma: "你每天怎么去学校？", pinyin: "Nǐ měitiān zěnme qù xuéxiào?", traducao: "Como você vai para a escola todos os dias?" },
    { ideograma: "我坐公交车去学校。", pinyin: "Wǒ zuò gōngjiāochē qù xuéxiào.", traducao: "Eu pego o ônibus para a escola." },
    { ideograma: "你认识这个人吗？", pinyin: "Nǐ rènshi zhège rén ma?", traducao: "Você conhece essa pessoa?" },
    { ideograma: "我不认识他。", pinyin: "Wǒ bú rènshi tā.", traducao: "Eu não o conheço." },
    { ideograma: "这个东西贵不贵？", pinyin: "Zhège dōngxi guì bú guì?", traducao: "Esta coisa é cara?" },
    { ideograma: "不太贵，很便宜。", pinyin: "Bú tài guì, hěn piányi.", traducao: "Não é muito caro, é barato." },
    { ideograma: "你喜欢吃什么水果？", pinyin: "Nǐ xǐhuan chī shénme shuǐguǒ?", traducao: "Que frutas você gosta de comer?" },
    { ideograma: "我喜欢吃西瓜和苹果。", pinyin: "Wǒ xǐhuan chī xīguā hé píngguǒ.", traducao: "Eu gosto de melancia e maçã." },
    { ideograma: "你去哪儿？", pinyin: "Nǐ qù nǎr?", traducao: "Para onde você está indo?" },
    { ideograma: "我去超市买东西。", pinyin: "Wǒ qù chāoshì mǎi dōngxi.", traducao: "Estou indo ao mercado comprar coisas." },
    { ideograma: "天气怎么样？", pinyin: "Tiānqì zěnmeyàng?", traducao: "Como está o tempo?" },
    { ideograma: "你有多少钱？", pinyin: "Nǐ yǒu duōshǎo qián?", traducao: "Quanto dinheiro você tem?" },
    { ideograma: "今天很冷。", pinyin: "Jīntiān hěn lěng.", traducao: "Hoje está muito frio." },
    { ideograma: "我只有五十块钱。", pinyin: "Wǒ zhǐ yǒu wǔshí kuài qián.", traducao: "Eu só tenho cinquenta yuans." },
    { ideograma: "你喜欢哪个季节？", pinyin: "Nǐ xǐhuan nǎge jìjié?", traducao: "Qual estação do ano você gosta?" },
    { ideograma: "我最喜欢春天。", pinyin: "Wǒ zuì xǐhuan chūntiān.", traducao: "Eu gosto mais da primavera." },
    { ideograma: "你的手机号码是多少？", pinyin: "Nǐ de shǒujī hàomǎ shì duōshǎo?", traducao: "Qual é o seu número de telefone?" },
    { ideograma: "我的号码是123456789。", pinyin: "Wǒ de hàomǎ shì yī èr sān sì wǔ liù qī bā jiǔ.", traducao: "Meu número é 123456789." },
    { ideograma: "你会弹钢琴吗？", pinyin: "Nǐ huì tán gāngqín ma?", traducao: "Você sabe tocar piano?" },
    { ideograma: "我不会弹钢琴。", pinyin: "Wǒ bú huì tán gāngqín.", traducao: "Eu não sei tocar piano." },
    { ideograma: "你平时几点睡觉？", pinyin: "Nǐ píngshí jǐ diǎn shuìjiào?", traducao: "Normalmente, que horas você dorme?" },
    { ideograma: "我晚上十一点睡觉。", pinyin: "Wǒ wǎnshàng shíyī diǎn shuìjiào.", traducao: "Eu durmo às onze da noite." },
    { ideograma: "你觉得这家餐厅怎么样？", pinyin: "Nǐ juéde zhè jiā cāntīng zěnmeyàng?", traducao: "O que você acha deste restaurante?" },
    { ideograma: "这家餐厅的饭很好吃。", pinyin: "Zhè jiā cāntīng de fàn hěn hǎochī.", traducao: "A comida deste restaurante é deliciosa." },
    { ideograma: "你最近怎么样？", pinyin: "Nǐ zuìjìn zěnmeyàng?", traducao: "Como você tem estado ultimamente?" },
    { ideograma: "我最近很忙，但是很好。", pinyin: "Wǒ zuìjìn hěn máng, dànshì hěn hǎo.", traducao: "Tenho estado ocupado, mas estou bem." },
    { ideograma: "你周末有什么计划？", pinyin: "Nǐ zhōumò yǒu shénme jìhuà?", traducao: "Quais são seus planos para o fim de semana?" },
    { ideograma: "我打算去看电影。", pinyin: "Wǒ dǎsuàn qù kàn diànyǐng.", traducao: "Eu planejo ir ao cinema." },
    { ideograma: "你会骑自行车吗？", pinyin: "Nǐ huì qí zìxíngchē ma?", traducao: "Você sabe andar de bicicleta?" },
    { ideograma: "我会骑自行车，但是骑得不太好。", pinyin: "Wǒ huì qí zìxíngchē, dànshì qí de bú tài hǎo.", traducao: "Eu sei andar de bicicleta, mas não muito bem." },
    { ideograma: "你家离学校远吗？", pinyin: "Nǐ jiā lí xuéxiào yuǎn ma?", traducao: "Sua casa é longe da escola?" },
    { ideograma: "我家离学校很近。", pinyin: "Wǒ jiā lí xuéxiào hěn jìn.", traducao: "Minha casa é perto da escola." },
    { ideograma: "你喜欢听什么音乐？", pinyin: "Nǐ xǐhuan tīng shénme yīnyuè?", traducao: "Que tipo de música você gosta de ouvir?" },
    { ideograma: "我喜欢听流行音乐。", pinyin: "Wǒ xǐhuan tīng liúxíng yīnyuè.", traducao: "Eu gosto de ouvir música pop." },
    { ideograma: "你常常运动吗？", pinyin: "Nǐ chángcháng yùndòng ma?", traducao: "Você se exercita com frequência?" },
    { ideograma: "我每周运动三次。", pinyin: "Wǒ měi zhōu yùndòng sān cì.", traducao: "Eu me exercito três vezes por semana." },
    { ideograma: "你今天几点起床？", pinyin: "Nǐ jīntiān jǐ diǎn qǐchuáng?", traducao: "Que horas você acordou hoje?" },
    { ideograma: "我今天早上六点起床。", pinyin: "Wǒ jīntiān zǎoshang liù diǎn qǐchuáng.", traducao: "Hoje acordei às seis da manhã." },
    { ideograma: "你的生日是什么时候？", pinyin: "Nǐ de shēngrì shì shénme shíhòu?", traducao: "Quando é o seu aniversário?" },
    { ideograma: "我的生日是八月二十号。", pinyin: "Wǒ de shēngrì shì bā yuè èrshí hào.", traducao: "Meu aniversário é no dia 20 de agosto." },
    { ideograma: "你周末喜欢做什么？", pinyin: "Nǐ zhōumò xǐhuan zuò shénme?", traducao: "O que você gosta de fazer nos fins de semana?" },
    { ideograma: "我喜欢看电影和逛街。", pinyin: "Wǒ xǐhuan kàn diànyǐng hé guàngjiē.", traducao: "Eu gosto de assistir filmes e passear." },
    { ideograma: "你喝酒吗？", pinyin: "Nǐ hē jiǔ ma?", traducao: "Você bebe álcool?" },
    { ideograma: "我不喝酒。", pinyin: "Wǒ bù hē jiǔ.", traducao: "Eu não bebo álcool." },
    { ideograma: "你喜欢喝什么饮料？", pinyin: "Nǐ xǐhuan hē shénme yǐnliào?", traducao: "Qual bebida você gosta de beber?" },
    { ideograma: "我喜欢喝果汁。", pinyin: "Wǒ xǐhuan hē guǒzhī.", traducao: "Eu gosto de beber suco." },
    { ideograma: "你喜欢吃甜的吗？", pinyin: "Nǐ xǐhuan chī tián de ma?", traducao: "Você gosta de doces?" },
    { ideograma: "我很喜欢吃巧克力。", pinyin: "Wǒ hěn xǐhuan chī qiǎokèlì.", traducao: "Eu gosto muito de chocolate." },
    { ideograma: "你会跳舞吗？", pinyin: "Nǐ huì tiàowǔ ma?", traducao: "Você sabe dançar?" },
    { ideograma: "我不会跳舞。", pinyin: "Wǒ bú huì tiàowǔ.", traducao: "Eu não sei dançar." },
    { ideograma: "你喜欢看书还是看电影？", pinyin: "Nǐ xǐhuan kàn shū háishì kàn diànyǐng?", traducao: "Você prefere ler livros ou assistir filmes?" },
    { ideograma: "我更喜欢看电影。", pinyin: "Wǒ gèng xǐhuan kàn diànyǐng.", traducao: "Eu prefiro assistir filmes." },
    { ideograma: "你喜欢吃中餐还是西餐？", pinyin: "Nǐ xǐhuan chī zhōngcān háishì xīcān?", traducao: "Você prefere comida chinesa ou ocidental?" },
    { ideograma: "我更喜欢中餐。", pinyin: "Wǒ gèng xǐhuan zhōngcān.", traducao: "Eu prefiro comida chinesa." },
    { ideograma: "你有兄弟姐妹吗？", pinyin: "Nǐ yǒu xiōngdì jiěmèi ma?", traducao: "Você tem irmãos?" },
    { ideograma: "我有一个妹妹。", pinyin: "Wǒ yǒu yí gè mèimei.", traducao: "Eu tenho uma irmã mais nova." },
    { ideograma: "你会说几种语言？", pinyin: "Nǐ huì shuō jǐ zhǒng yǔyán?", traducao: "Quantos idiomas você fala?" },
    { ideograma: "我会说三种语言。", pinyin: "Wǒ huì shuō sān zhǒng yǔyán.", traducao: "Eu falo três idiomas." },
    { ideograma: "你每天几点上班？", pinyin: "Nǐ měitiān jǐ diǎn shàngbān?", traducao: "Que horas você vai para o trabalho todos os dias?" },
    { ideograma: "我早上九点上班。", pinyin: "Wǒ zǎoshang jiǔ diǎn shàngbān.", traducao: "Eu começo a trabalhar às nove da manhã." },
    { ideograma: "你周末加班吗？", pinyin: "Nǐ zhōumò jiābān ma?", traducao: "Você faz hora extra nos fins de semana?" },
    { ideograma: "我有时候加班。", pinyin: "Wǒ yǒu shíhou jiābān.", traducao: "Às vezes eu faço hora extra." },
    { ideograma: "你喜欢什么样的天气？", pinyin: "Nǐ xǐhuan shénme yàng de tiānqì?", traducao: "Que tipo de clima você gosta?" },
    { ideograma: "我喜欢凉爽的天气。", pinyin: "Wǒ xǐhuan liángshuǎng de tiānqì.", traducao: "Eu gosto de clima fresco." },
    { ideograma: "你会自己做饭吗？", pinyin: "Nǐ huì zìjǐ zuò fàn ma?", traducao: "Você sabe cozinhar sozinho?" },
    { ideograma: "我会做简单的饭菜。", pinyin: "Wǒ huì zuò jiǎndān de fàncài.", traducao: "Eu sei cozinhar pratos simples." },
    { ideograma: "你去过哪些国家？", pinyin: "Nǐ qù guò nǎxiē guójiā?", traducao: "Quais países você já visitou?" },
    { ideograma: "我去过法国和美国。", pinyin: "Wǒ qù guò Fǎguó hé Měiguó.", traducao: "Eu já fui para a França e os Estados Unidos." },
    { ideograma: "你常常旅行吗？", pinyin: "Nǐ chángcháng lǚxíng ma?", traducao: "Você viaja com frequência?" },
    { ideograma: "我不常旅行。", pinyin: "Wǒ bù cháng lǚxíng.", traducao: "Eu não viajo com frequência." },
    { ideograma: "你喜欢住酒店还是民宿？", pinyin: "Nǐ xǐhuan zhù jiǔdiàn háishì mínsù?", traducao: "Você prefere ficar em hotéis ou pousadas?" },
    { ideograma: "我更喜欢住民宿。", pinyin: "Wǒ gèng xǐhuan zhù mínsù.", traducao: "Eu prefiro ficar em pousadas." }
  
  
  ];
  